---
localhost
  vars:
    MASTERNODE: "Copy/Paste in the MN token.  It can be found at https://poseidon.pirl.io/accounts/masternodes-list-private/"
    TOKEN: "Copy/Paste in your POSEIDON account's token.  It can be found at https://poseidon.pirl.io/accounts/settings/"
    RUNAS_USER: pirl
