---
- hosts: localhost
  pre_tasks:
    - name: APT DIST-UPGRADE
      apt:
        update_cache: yes
        upgrade: dist
      become: yes

    - name: INSTALL REQUIRED PACKAGES
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: "{{ packages }}"

    - name: INSTALL REQUIRED PYTHON MODULES
      pip:
        requirements: requirements.txt

  tasks:
    - name: CONFIGURE USER FOR PIRL MASTERNODE SERVICE
      user:
        name: "{{RUNAS_USER}}"
        state: present
        shell: /usr/sbin/nologin

    - name: SET UP UFW
      include_role:
        name: ufw

    - name: INSTALL PIRL MASTERNODE BINARY
      include_role:
        name: pirl_mn
      when: "{{ MASTERNODE }} and {{ TOKEN }}"
