---
- name: GET REAL RAM AMOUNT
  shell: grep MemTotal /proc/meminfo |  sed 's/[^0-9]*//g'
  register: total_ram

- name: OUTPUT RAM AMOUNT
  debug:
    msg: "Your total ram is: {{ total_ram.stdout }}"

- name: ENSURE WE HAVE AT LEAST 4GB RAM
  assert:
    that:
      - "{{ total_ram.stdout }} >= 4000000"
