---
- name: CONFIGURE UFW UDP PORTS
  ufw:
    rule: allow
    proto: udp
    port: "{{ item }}"
  with_items:
    - 30303

- name: CONFIGURE UFW TCP PORTS
  ufw:
    rule: allow
    proto: udp
    port: "{{ item }}"
  with_items:
    - 30303
    - 22

- name: ENABLE UFW
  ufw:
    state: enabled
    policy: deny

- name: CONFIGURE UFW TO ONLY ALLOW YOUR_IP SSH ACCESS
  ufw:
    rule: allow
    src: "{{ YOUR_IP }}"
  when: "({{ YOUR_IP }} != a.b.c.d) and {{ YOUR_IP | ipaddr.is_unicast }}"
