---
- name: CHECK EXISTENCE OF PREVIOUS PIRL MASTERNODE INSTALLATION
  stat:
    path: /etc/systemd/system/pirlnode.service
  register: pirl_systemd_file

- name: STOP EXISTING PIRL MASTERNODE
  systemd:
    name: pirlnode.service
    state: stopped
  when: pirl_systemd_file.stat.exists == True

- name: DOWNLOAD PIRL MASTERNODE BINARY
  get_url:
    url: "{{pirl_mn_binary_url}}"
    dest: /usr/local/bin/pirl-linux-amd64
    mode: 0755

- name: SET UP PIRLNODE-ENV FILE
  template:
    src: templates/pirlnode-env.j2
    dest: /etc/pirlnode-env
    owner: "{{ RUNAS_USER }}"
    group: "{{ RUNAS_USER }}"
    mode: 0644

- name: CONFIGURE SYSTEMD FOR PIRL BINARY
  template:
    src: templates/unit_file.j2
    dest: /etc/systemd/system/pirlnode.service
    owner: "{{ RUNAS_USER }}"
    group: "{{ RUNAS_USER }}"
    mode: 0755

- name: RELOAD SYSTEMD
  systemd:
    daemon_reload: yes

- name: ENABLE AND START THE PIRLNODE SERVICE
  systemd:
    name: pirlnode.service
    state: started
    enabled: yes
